const cards = [
  [
    {
      word: 'Action (set A)',
      image: './assets/images/hug.jpg',
    },
    {
      word: 'Action (set B)',
      image: './assets/images/swim.jpg',
    },
    {
      word: 'Animal (set A)',
      image: './assets/images/rabbit.jpg',
    },
    {
      word: 'Animal (set B)',
      image: './assets/images/bird.jpg',
    },
    {
      word: 'Clothes',
      image: './assets/images/blouse.jpg',
    },
    {
      word: 'Emotions',
      image: './assets/images/cry.jpg',
    },
    {
      word: 'Food',
      image: './assets/images/eggs.jpg',
    },
    {
      word: 'Fruits',
      image: './assets/images/mango.jpg',
    },
  ],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: './assets/images/cry.jpg',
      audioSrc: 'audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: './assets/images/dance.jpg',
      audioSrc: 'audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: './assets/images/dive.jpg',
      audioSrc: 'audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: './assets/images/draw.jpg',
      audioSrc: 'audio/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: './assets/images/fish.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: './assets/images/fly.jpg',
      audioSrc: 'audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: './assets/images/hug.jpg',
      audioSrc: 'audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: './assets/images/jump.jpg',
      audioSrc: 'audio/jump.mp3',
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      image: './assets/images/open.jpg',
      audioSrc: 'audio/open.mp3',
    },
    {
      word: 'play',
      translation: 'играть',
      image: './assets/images/play.jpg',
      audioSrc: 'audio/play.mp3',
    },
    {
      word: 'point',
      translation: 'указывать',
      image: './assets/images/point.jpg',
      audioSrc: 'audio/point.mp3',
    },
    {
      word: 'ride',
      translation: 'ездить',
      image: './assets/images/ride.jpg',
      audioSrc: 'audio/ride.mp3',
    },
    {
      word: 'run',
      translation: 'бегать',
      image: './assets/images/run.jpg',
      audioSrc: 'audio/run.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: './assets/images/sing.jpg',
      audioSrc: 'audio/sing.mp3',
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      image: './assets/images/skip.jpg',
      audioSrc: 'audio/skip.mp3',
    },
    {
      word: 'swim',
      translation: 'плавать',
      image: './assets/images/swim.jpg',
      audioSrc: 'audio/swim.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: './assets/images/cat.jpg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: './assets/images/chick.jpg',
      audioSrc: 'audio/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: './assets/images/chicken.jpg',
      audioSrc: 'audio/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './assets/images/dog.jpg',
      audioSrc: 'audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: './assets/images/horse.jpg',
      audioSrc: 'audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './assets/images/pig.jpg',
      audioSrc: 'audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: './assets/images/rabbit.jpg',
      audioSrc: 'audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: './assets/images/sheep.jpg',
      audioSrc: 'audio/sheep.mp3',
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      image: './assets/images/bird.jpg',
      audioSrc: 'audio/bird.mp3',
    },
    {
      word: 'fish',
      translation: 'рыба',
      image: './assets/images/fish1.jpg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'frog',
      translation: 'жаба',
      image: './assets/images/frog.jpg',
      audioSrc: 'audio/frog.mp3',
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      image: './assets/images/giraffe.jpg',
      audioSrc: 'audio/giraffe.mp3',
    },
    {
      word: 'lion',
      translation: 'лев',
      image: './assets/images/lion.jpg',
      audioSrc: 'audio/lion.mp3',
    },
    {
      word: 'mouse',
      translation: 'мышь',
      image: './assets/images/mouse.jpg',
      audioSrc: 'audio/mouse.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: './assets/images/turtle.jpg',
      audioSrc: 'audio/turtle.mp3',
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      image: './assets/images/dolphin.jpg',
      audioSrc: 'audio/dolphin.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: './assets/images/skirt.jpg',
      audioSrc: 'audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: './assets/images/pants.jpg',
      audioSrc: 'audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: './assets/images/blouse.jpg',
      audioSrc: 'audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: './assets/images/dress.jpg',
      audioSrc: 'audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: './assets/images/boot.jpg',
      audioSrc: 'audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: './assets/images/shirt.jpg',
      audioSrc: 'audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: './assets/images/coat.jpg',
      audioSrc: 'audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: './assets/images/shoe.jpg',
      audioSrc: 'audio/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: './assets/images/sad.jpg',
      audioSrc: 'audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: './assets/images/angry.jpg',
      audioSrc: 'audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: './assets/images/happy.jpg',
      audioSrc: 'audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: './assets/images/tired.jpg',
      audioSrc: 'audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: './assets/images/surprised.jpg',
      audioSrc: 'audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: './assets/images/scared.jpg',
      audioSrc: 'audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: './assets/images/smile.jpg',
      audioSrc: 'audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: './assets/images/laugh.jpg',
      audioSrc: 'audio/laugh.mp3',
    },
  ],
  [
    {
      word: 'hamburger',
      translation: 'гамбургер',
      image: './assets/images/hamburger.jpg',
      audioSrc: 'audio/hamburger.mp3',
    },
    {
      word: 'ice-cream',
      translation: 'мороженое',
      image: './assets/images/ice-cream.jpg',
      audioSrc: 'audio/ice-cream.mp3',
    },
    {
      word: 'cheese',
      translation: 'сыр',
      image: './assets/images/cheese.jpg',
      audioSrc: 'audio/cheese.mp3',
    },
    {
      word: 'pizza',
      translation: 'пицца',
      image: './assets/images/pizza.jpg',
      audioSrc: 'audio/pizza.mp3',
    },
    {
      word: 'eggs',
      translation: 'яйца',
      image: './assets/images/eggs.jpg',
      audioSrc: 'audio/eggs.mp3',
    },
    {
      word: 'chocolate',
      translation: 'шоколад',
      image: './assets/images/chocolate.jpg',
      audioSrc: 'audio/chocolate.mp3',
    },
    {
      word: 'rice',
      translation: 'рис',
      image: './assets/images/rice.jpg',
      audioSrc: 'audio/rice.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: './assets/images/bread.jpg',
      audioSrc: 'audio/bread.mp3',
    },
  ],
  [
    {
      word: 'grapes',
      translation: 'виноград',
      image: './assets/images/grapes.jpg',
      audioSrc: 'audio/grapes.mp3',
    },
    {
      word: 'apple',
      translation: 'яблоко',
      image: './assets/images/apple.jpg',
      audioSrc: 'audio/apple.mp3',
    },
    {
      word: 'pear',
      translation: 'груша',
      image: './assets/images/pear.jpg',
      audioSrc: 'audio/pear.mp3',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: './assets/images/banana.jpg',
      audioSrc: 'audio/banana.mp3',
    },
    {
      word: 'melon',
      translation: 'дыня',
      image: './assets/images/melon.jpg',
      audioSrc: 'audio/melon.mp3',
    },
    {
      word: 'mango',
      translation: 'манго',
      image: './assets/images/mango.jpg',
      audioSrc: 'audio/mango.mp3',
    },
    {
      word: 'kiwi',
      translation: 'киви',
      image: './assets/images/kiwi.jpg',
      audioSrc: 'audio/kiwi.mp3',
    },
    {
      word: 'plum',
      translation: 'слива',
      image: './assets/images/plum.jpg',
      audioSrc: 'audio/plum.mp3',
    },
  ],
]


export default cards
